Add AWS tests using static credentials or STS.
* Run hybrid tests in ci, using separate realm on testing.katta.cloud.
* Extract .local.env for LOCAL integration tests.
* Add .hybrid.env. Refactor reverse proxy configurations.
* Inject HUB_KEYCLOAK_URL and HUB_KEYCLOAK_REALM.

diff --git a/docker-compose-minio-localhost-hub.yml b/docker-compose-minio-localhost-hub.yml
--- a/docker-compose-minio-localhost-hub.yml
+++ b/docker-compose-minio-localhost-hub.yml
@@ -4,8 +4,8 @@ services:
     image: "${KATTA_KEYCLOAK_IMAGE}"
     pull_policy: missing
     ports:
-      - "${KEYCLOAK_HTTP_PORT}:${KEYCLOAK_HTTP_PORT}"
-      - "${KEYCLOAK_HTTPS_PORT}:8443"
+      - "${KEYCLOAK_HTTP_PORT:-1}:${KEYCLOAK_HTTP_PORT:-1}"
+      - "${KEYCLOAK_HTTPS_PORT:-1}:8443"
     environment:
       KEYCLOAK_ADMIN: admin
       KEYCLOAK_ADMIN_PASSWORD: admin
@@ -27,6 +27,7 @@ services:
       timeout: 10s
       retries: 15
 
+
   keycloak-enable-direct-access-grant:
     profiles: [ local ]
     image: "${KATTA_KEYCLOAK_IMAGE}"
@@ -47,6 +48,39 @@ services:
     depends_on:
       keycloak:
         condition: service_healthy
+
+  keycloak-ready:
+    image: nginx
+    volumes:
+      - ./docker/nginx/keycloak.conf.template:/etc/nginx/conf.d/keycloak.conf.template:ro
+    entrypoint: [ "/bin/bash","-c" ]
+    command:
+      - |
+        set -euxo pipefail
+
+        apt-get update && apt-get install -y wget
+
+        if [ -n "${KEYCLOAK_HOSTNAME}" ]; then
+          # inject ports
+          export KEYCLOAK_HTTP_PORT=${KEYCLOAK_HTTP_PORT}
+          # see https://stackoverflow.com/questions/56649582/substitute-environment-variables-in-nginx-config-from-docker-compose
+          # see https://www.baeldung.com/linux/envsubst-command
+          # https://stackoverflow.com/questions/24963705/is-there-an-escape-character-for-envsubst
+          envsubst < /etc/nginx/conf.d/keycloak.conf.template >> /etc/nginx/conf.d/default.conf
+          cat /etc/nginx/conf.d/default.conf
+          # reload and verify configuration
+          nginx -t
+          # start reverse proxy to keycloak and hub
+          nginx
+        fi
+
+        until wget -q -O- ${HUB_KEYCLOAK_URL}${HUB_KEYCLOAK_BASEPATH}/realms/${HUB_KEYCLOAK_REALM}/.well-known/openid-configuration >/dev/null 2>&1; do sleep 1; done
+    healthcheck:
+      test: [ "CMD-SHELL", "exit 0" ]
+      interval: 10s
+      timeout: 1s
+      retries: 15
+
   postgres:
     image:
       docker.io/postgres:14
@@ -73,8 +107,8 @@ services:
     build:
       dockerfile: docker/minio/Dockerfile
     depends_on:
-      keycloak:
-        condition: service_healthy
+      keycloak-ready:
+        condition: service_completed_successfully
     restart: on-failure
     ports:
       - "${MINIO_PORT}:${MINIO_PORT}"
@@ -89,25 +123,27 @@ services:
       timeout: 1s
       retries: 5
     volumes:
-      - ./docker/minio/nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template:ro
+      - ./docker/nginx/keycloak.conf.template:/etc/nginx/conf.d/keycloak.conf.template:ro
     entrypoint: [ "/bin/bash","-c" ]
     command:
       - |
         set -euxo pipefail
 
-        # inject ports
-        # see https://stackoverflow.com/questions/56649582/substitute-environment-variables-in-nginx-config-from-docker-compose
-        # see https://www.baeldung.com/linux/envsubst-command
-        # https://stackoverflow.com/questions/24963705/is-there-an-escape-character-for-envsubst
-        envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf
-        cat /etc/nginx/conf.d/default.conf
-        # reload and verify configuration
-        nginx -t
-        # start reverse proxy to keycloak
-        systemctl start nginx.service
-        # verify reverse proxy
-        curl --fail http://localhost:${KEYCLOAK_HTTP_PORT}/realms/cryptomator/.well-known/openid-configuration
-        curl --fail http://127.0.0.1:${KEYCLOAK_HTTP_PORT}/realms/cryptomator/.well-known/openid-configuration
+        if [ -n "${KEYCLOAK_HOSTNAME}" ]; then
+          # inject ports
+          # see https://stackoverflow.com/questions/56649582/substitute-environment-variables-in-nginx-config-from-docker-compose
+          # see https://www.baeldung.com/linux/envsubst-command
+          # https://stackoverflow.com/questions/24963705/is-there-an-escape-character-for-envsubst
+          envsubst < /etc/nginx/conf.d/keycloak.conf.template >> /etc/nginx/conf.d/default.conf
+          cat /etc/nginx/conf.d/default.conf
+          # reload and verify configuration
+          nginx -t
+          # start reverse proxy to keycloak
+          systemctl start nginx.service
+          # verify reverse proxy
+          curl --fail http://localhost:${KEYCLOAK_HTTP_PORT}/realms/cryptomator/.well-known/openid-configuration
+          curl --fail http://127.0.0.1:${KEYCLOAK_HTTP_PORT}/realms/cryptomator/.well-known/openid-configuration
+        fi
 
         /minio server /data --address :${MINIO_PORT} --console-address :${MINIO_CONSOLE_PORT}
 
@@ -117,11 +153,11 @@ services:
     depends_on:
       minio:
         condition: service_healthy
-      keycloak:
-        condition: service_healthy
+      keycloak-ready:
+        condition: service_completed_successfully
     volumes:
       - ./setup:/setup
-      - ./docker/minio/nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template:ro
+      - ./docker/nginx/keycloak.conf.template:/etc/nginx/conf.d/keycloak.conf.template:ro
     environment:
       KEYCLOAK_HTTP_PORT: ${KEYCLOAK_HTTP_PORT}
       KEYCLOAK_HOSTNAME: ${KEYCLOAK_HOSTNAME}
@@ -130,19 +166,21 @@ services:
       - |
         set -euxo pipefail
 
-        # inject ports
-        # see https://stackoverflow.com/questions/56649582/substitute-environment-variables-in-nginx-config-from-docker-compose
-        # see https://www.baeldung.com/linux/envsubst-command
-        # https://stackoverflow.com/questions/24963705/is-there-an-escape-character-for-envsubst
-        envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf
-        cat /etc/nginx/conf.d/default.conf
-        # reload and verify configuration
-        nginx -t
-        # start reverse proxy to keycloak
-        systemctl start nginx.service
-        # verify reverse proxy
-        curl --fail http://localhost:${KEYCLOAK_HTTP_PORT}/realms/cryptomator/.well-known/openid-configuration
-        curl --fail http://127.0.0.1:${KEYCLOAK_HTTP_PORT}/realms/cryptomator/.well-known/openid-configuration
+        if [ -n "${KEYCLOAK_HOSTNAME}" ]; then
+          # inject ports
+          # see https://stackoverflow.com/questions/56649582/substitute-environment-variables-in-nginx-config-from-docker-compose
+          # see https://www.baeldung.com/linux/envsubst-command
+          # https://stackoverflow.com/questions/24963705/is-there-an-escape-character-for-envsubst
+          envsubst < /etc/nginx/conf.d/keycloak.conf.template >> /etc/nginx/conf.d/default.conf
+          cat /etc/nginx/conf.d/default.conf
+          # reload and verify configuration
+          nginx -t
+          # start reverse proxy to keycloak
+          systemctl start nginx.service
+          # verify reverse proxy
+          curl --fail http://localhost:${KEYCLOAK_HTTP_PORT}/realms/cryptomator/.well-known/openid-configuration
+          curl --fail http://127.0.0.1:${KEYCLOAK_HTTP_PORT}/realms/cryptomator/.well-known/openid-configuration
+        fi
 
         ls /setup
         /mc config host add myminio http://minio:${MINIO_PORT} minioadmin minioadmin
@@ -150,20 +188,19 @@ services:
         /mc admin policy create myminio cipherduckcreatebucket /setup/minio_sts/createbucketpolicy.json
         /mc admin policy create myminio cipherduckaccessbucket /setup/minio_sts/accessbucketpolicy.json
 
-        curl --fail http://localhost:${KEYCLOAK_HTTP_PORT}/realms/cryptomator/.well-known/openid-configuration
 
         /mc idp openid add myminio cryptomator \
-          config_url="http://${KEYCLOAK_HOSTNAME}:${KEYCLOAK_HTTP_PORT}/realms/cryptomator/.well-known/openid-configuration" \
+          config_url="${HUB_KEYCLOAK_URL}${HUB_KEYCLOAK_BASEPATH}/realms/${HUB_KEYCLOAK_REALM}/.well-known/openid-configuration" \
           client_id="cryptomator" \
           client_secret="ignore-me" \
           role_policy="cipherduckcreatebucket"
         /mc idp openid add myminio cryptomatorhub \
-          config_url="http://${KEYCLOAK_HOSTNAME}:${KEYCLOAK_HTTP_PORT}/realms/cryptomator/.well-known/openid-configuration" \
+          config_url="${HUB_KEYCLOAK_URL}${HUB_KEYCLOAK_BASEPATH}/realms/${HUB_KEYCLOAK_REALM}/.well-known/openid-configuration" \
           client_id="cryptomatorhub" \
           client_secret="ignore-me" \
           role_policy="cipherduckcreatebucket"
         /mc idp openid add myminio cryptomatorvaults \
-          config_url="http://${KEYCLOAK_HOSTNAME}:${KEYCLOAK_HTTP_PORT}/realms/cryptomator/.well-known/openid-configuration" \
+          config_url="${HUB_KEYCLOAK_URL}${HUB_KEYCLOAK_BASEPATH}/realms/${HUB_KEYCLOAK_REALM}/.well-known/openid-configuration" \
           client_id="cryptomatorvaults" \
           client_secret="ignore-me" \
           role_policy="cipherduckaccessbucket"
@@ -195,9 +232,11 @@ services:
       args:
         KATTA_SERVER_IMAGE: "${KATTA_SERVER_IMAGE}"
     depends_on:
-      keycloak:
-        condition: service_healthy
+      keycloak-ready:
+        condition: service_completed_successfully
       postgres:
+        condition: service_healthy
+      minio:
         condition: service_healthy
     healthcheck:
       test: [ "CMD", "bash", "-c", "curl -v --fail 127.0.0.1:${HUB_PORT}/api/config" ]
@@ -207,48 +246,71 @@ services:
     environment:
       QUARKUS_PROFILE: dev
       QUARKUS_HTTP_PORT: ${HUB_PORT}
-      QUARKUS_OIDC_AUTH_SERVER_URL: http://${KEYCLOAK_HOSTNAME}:${KEYCLOAK_HTTP_PORT}/realms/cryptomator
+      QUARKUS_OIDC_AUTH_SERVER_URL: ${HUB_KEYCLOAK_URL}${HUB_KEYCLOAK_BASEPATH}/realms/${HUB_KEYCLOAK_REALM}
       QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/quarkus
       QUARKUS_DATASOURCE_USERNAME: quarkus
       QUARKUS_DATASOURCE_PASSWORD: quarkus
       QUARKUS_LOG_LEVEL: DEBUG
       # allow calls from frontend localhost:8280 to keycloak:8380 and minio:9000 when using interactively (attended),
       # dev-ui needs very permissive CSP:
-      QUARKUS_HTTP_HEADER__CONTENT_SECURITY_POLICY__VALUE: "default-src 'self' 'unsafe-inline' 'unsafe-eval' blob: data:; connect-src 'self'  ${MINIO_HOSTNAME}:${MINIO_PORT} ${KEYCLOAK_HOSTNAME}:${KEYCLOAK_HTTP_PORT}; object-src 'none'; child-src 'self'; img-src * data:; frame-ancestors 'none'"
+      QUARKUS_HTTP_HEADER__CONTENT_SECURITY_POLICY__VALUE: "default-src 'self' 'unsafe-inline' 'unsafe-eval' blob: data:; connect-src 'self'  ${MINIO_HOSTNAME}:${MINIO_PORT} ${HUB_KEYCLOAK_URL}; object-src 'none'; child-src 'self'; img-src * data:; frame-ancestors 'none'"
       QUARKUS_SWAGGER_UI_ALWAYS_INCLUDE: true
       QUARKUS_SWAGGER_UI_ENABLE: true
       QUARKUS_SWAGGER_UI_OAUTH_USE_PKCE_WITH_AUTHORIZATION_CODE_GRANT: true
       QUARKUS_SWAGGER_UI_TITLE: Katta Server API
       QUARKUS_SWAGGER_UI_PREAUTHORIZE_BASIC_USERNAME: admin
       QUARKUS_SWAGGER_UI_PREAUTHORIZE_BASIC_PASSWORD: admin
-      HUB_KEYCLOAK_PUBLIC_URL: http://${KEYCLOAK_HOSTNAME}:${KEYCLOAK_HTTP_PORT}
-      HUB_KEYCLOAK_LOCAL_URL: http://${KEYCLOAK_HOSTNAME}:${KEYCLOAK_HTTP_PORT}
+
+      HUB_KEYCLOAK_PUBLIC_URL: ${HUB_KEYCLOAK_URL}${HUB_KEYCLOAK_BASEPATH}
+      HUB_KEYCLOAK_LOCAL_URL: ${HUB_KEYCLOAK_URL}${HUB_KEYCLOAK_BASEPATH}
+      HUB_KEYCLOAK_REALM: ${HUB_KEYCLOAK_REALM}
+      HUB_KEYCLOAK_SYNCER_PASSWORD: ${HUB_KEYCLOAK_SYNCER_PASSWORD}
       HUB_KEYCLOAK_OIDC_CRYPTOMATOR_CLIENT_ID: cryptomator
       AWS_REGION: us-east-1
-      KEYCLOAK_HTTP_PORT: ${KEYCLOAK_HTTP_PORT}
-      MINIO_PORT: ${MINIO_PORT}
     ports:
       - "${HUB_PORT}:${HUB_PORT}"
     volumes:
-      - ./docker/hub/nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template:ro
+      - ./docker/nginx/keycloak.conf.template:/etc/nginx/conf.d/keycloak.conf.template:ro
+      - ./docker/nginx/minio.conf.template:/etc/nginx/conf.d/minio.conf.template:ro
     entrypoint: [ "/bin/bash","-c" ]
     command:
       - |
         set -euxo pipefail
 
+        if [ -n "${KEYCLOAK_HOSTNAME}" ]; then
+          # inject ports
+          export KEYCLOAK_HTTP_PORT=${KEYCLOAK_HTTP_PORT}
+
+          # see https://stackoverflow.com/questions/56649582/substitute-environment-variables-in-nginx-config-from-docker-compose
+          # see https://www.baeldung.com/linux/envsubst-command
+          # https://stackoverflow.com/questions/24963705/is-there-an-escape-character-for-envsubst
+          envsubst < /etc/nginx/conf.d/keycloak.conf.template >> /etc/nginx/conf.d/default.conf
+          cat /etc/nginx/conf.d/default.conf
+          # reload and verify configuration
+          nginx -t
+          # start reverse proxy to keycloak and minio
+          systemctl start nginx.service
+          # verify reverse proxy
+          curl --fail http://localhost:${KEYCLOAK_HTTP_PORT}/realms/cryptomator/.well-known/openid-configuration
+          curl --fail http://127.0.0.1:${KEYCLOAK_HTTP_PORT}/realms/cryptomator/.well-known/openid-configuration
+        fi
+
         # inject ports
+        export MINIO_PORT=${MINIO_PORT}
+
         # see https://stackoverflow.com/questions/56649582/substitute-environment-variables-in-nginx-config-from-docker-compose
         # see https://www.baeldung.com/linux/envsubst-command
         # https://stackoverflow.com/questions/24963705/is-there-an-escape-character-for-envsubst
-        envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf
+        envsubst < /etc/nginx/conf.d/minio.conf.template >> /etc/nginx/conf.d/default.conf
         cat /etc/nginx/conf.d/default.conf
         # reload and verify configuration
         nginx -t
         # start reverse proxy to keycloak and minio
-        systemctl start nginx.service
-        # verify reverse proxy
-        curl --fail http://localhost:${KEYCLOAK_HTTP_PORT}/realms/cryptomator/.well-known/openid-configuration
-        curl --fail http://127.0.0.1:${KEYCLOAK_HTTP_PORT}/realms/cryptomator/.well-known/openid-configuration
+        systemctl restart nginx.service
+        # skip verify reverse proxy (MinIO might not be up yet).
+        #        curl --fail http://localhost:${MINIO_PORT}/minio/health/ready
+        #        curl --fail http://127.0.0.1:${MINIO_PORT}/minio/health/ready
+
 
         java  -Djava.util.logging.manager=org.jboss.logmanager.LogManager -jar quarkus-run.jar
 
@@ -256,15 +318,14 @@ services:
     build:
       dockerfile: docker/hub_setup_storage_profile/Dockerfile
     depends_on:
-      keycloak:
-        condition: service_healthy
-      keycloak-enable-direct-access-grant:
+      keycloak-ready:
         condition: service_completed_successfully
       hub:
         condition: service_healthy
     volumes:
       - ./setup:/setup
-      - ./docker/hub_setup/nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template:ro
+      - ./docker/nginx/keycloak.conf.template:/etc/nginx/conf.d/keycloak.conf.template:ro
+      - ./docker/nginx/hub.conf.template:/etc/nginx/conf.d/hub.conf.template:ro
     entrypoint: [ "/bin/bash","-c" ]
     environment:
       KEYCLOAK_HTTP_PORT: ${KEYCLOAK_HTTP_PORT}
@@ -273,25 +334,41 @@ services:
       - |
         set -euxo pipefail
 
+        if [ -n "${KEYCLOAK_HOSTNAME}" ]; then
+          # inject ports
+          # see https://stackoverflow.com/questions/56649582/substitute-environment-variables-in-nginx-config-from-docker-compose
+          # see https://www.baeldung.com/linux/envsubst-command
+          # https://stackoverflow.com/questions/24963705/is-there-an-escape-character-for-envsubst
+          envsubst < /etc/nginx/conf.d/keycloak.conf.template >> /etc/nginx/conf.d/default.conf
+          cat /etc/nginx/conf.d/default.conf
+          # reload and verify configuration
+          nginx -t
+          # start reverse proxy to keycloak and hub
+          nginx -s quit || true
+          nginx
+        fi
+
+
         # inject ports
         # see https://stackoverflow.com/questions/56649582/substitute-environment-variables-in-nginx-config-from-docker-compose
         # see https://www.baeldung.com/linux/envsubst-command
         # https://stackoverflow.com/questions/24963705/is-there-an-escape-character-for-envsubst
-        envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf
+        envsubst < /etc/nginx/conf.d/hub.conf.template >> /etc/nginx/conf.d/default.conf
         cat /etc/nginx/conf.d/default.conf
         # reload and verify configuration
         nginx -t
         # start reverse proxy to keycloak and hub
+        nginx -s quit || true
         nginx
 
         ls /setup
         curl --version
-        curl -v -X POST http://${KEYCLOAK_HOSTNAME}:${KEYCLOAK_HTTP_PORT}/realms/cryptomator/protocol/openid-connect/token \
+        curl -v --fail -X POST ${HUB_KEYCLOAK_URL}${HUB_KEYCLOAK_BASEPATH}/realms/${HUB_KEYCLOAK_REALM}/protocol/openid-connect/token \
               -H "Content-Type: application/x-www-form-urlencoded" \
               -d "client_id=cryptomator" \
               -d "grant_type=password" \
-              -d "username=admin" \
-              -d "password=admin" > /tmp/access_token.txt
+              -d "username=${HUB_ADMIN_USER}" \
+              -d "password=${HUB_ADMIN_PASSWORD}" > /tmp/access_token.txt
         cat /tmp/access_token.txt
         export ACCESS_TOKEN=`cat /tmp/access_token.txt | jq ".access_token" | tr -d '"'`
 
@@ -314,3 +391,13 @@ services:
         condition: service_completed_successfully
       hub_setup_storage_profile:
         condition: service_completed_successfully
+    entrypoint: [ "sh","-c" ]
+    command:
+      - |
+        set -euxo pipefail
+        exit 0
+    healthcheck:
+      test: [ "CMD-SHELL", "exit 0" ]
+      interval: 10s
+      timeout: 1s
+      retries: 30
